# Generated by Django 6.1.1 on 2026-09-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('client', 'Cliente')], default='client', max_length=20),
        ),
    ]
