# Generated by Django 6.1.1 on 2026-09-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_de_servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofservice',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='typeofservice',
            name='with_roof',
            field=models.BooleanField(default=False),
        ),
    ]
