# Generated by Django 6.1.1 on 2026-09-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_de_servicio', '0002_typeofservice_price_per_hour_typeofservice_with_roof'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
