# Generated by Django 6.1.1 on 2026-09-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_de_servicio', '0003_typeofservice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
