# Generated by Django 6.1.1 on 2026-09-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_de_servicio', '0004_alter_typeofservice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
