# Generated by Django 6.1.1 on 2026-09-18 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_de_servicio', '0005_alter_typeofservice_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('daily', 'Diariamente'), ('weekly', 'Semanalmente (días específicos)')], max_length=20, verbose_name='Periodicidad')),
                ('days_of_week', models.JSONField(blank=True, default=list, verbose_name='Dias de la semana')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
                ('time_start', models.TimeField(verbose_name='Hora de inicio')),
                ('time_end', models.TimeField(verbose_name='Hora de finalización')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_reservations', to='tipo_de_servicio.typeofservice', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Reservación recurrente',
                'verbose_name_plural': 'Reservaciones recurrentes',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('status', models.CharField(choices=[('Disponible', 'Open'), ('tomada', 'Taken')], default='Disponible', max_length=10, verbose_name='Estado')),
                ('time_start', models.TimeField(verbose_name='Hora de inicio')),
                ('time_end', models.TimeField(verbose_name='Hora de finalización')),
                ('recurring_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_reservations', to='reservas.recurringreservation')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='tipo_de_servicio.typeofservice', verbose_name='Servicio')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
