# Generated by Django 6.1.1 on 2026-09-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('taken', 'Taken')], default='open', max_length=10, verbose_name='Estado'),
        ),
    ]
